import { isValidSession } from '../manage/_auth';

function cookies(header: string | string[] | undefined): Record<string, string> {
  const value = Array.isArray(header) ? header.join(';') : header ?? '';
  return Object.fromEntries(value.split(';').flatMap((part) => {
    const i = part.indexOf('=');
    if (i < 0) return [];
    return [[part.slice(0, i).trim(), decodeURIComponent(part.slice(i + 1).trim())]];
  }));
}
function escapeHtml(value: unknown): string {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char] ?? char));
}
export default async function handler(req: any, res: any): Promise<void> {
  if (req.method !== 'POST') { res.statusCode = 405; res.end('Method not allowed'); return; }
  if (!isValidSession(cookies(req.headers?.cookie)['hillview_manage_session'])) { res.statusCode = 401; res.end(JSON.stringify({ error: 'Staff authentication required' })); return; }
  const body = typeof req.body === 'string' ? JSON.parse(req.body || '{}') : (req.body ?? {});
  const to = typeof body.to === 'string' ? body.to.trim() : '';
  const bill = body.bill ?? {};
  const amount = Number(bill.amount);
  if (!to || !to.includes('@')) { res.statusCode = 400; res.end(JSON.stringify({ error: 'A valid customer email is required.' })); return; }
  if (!Number.isFinite(amount) || amount <= 0 || !bill.id) { res.statusCode = 400; res.end(JSON.stringify({ error: 'Invalid bill.' })); return; }
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.RESEND_FROM_EMAIL;
  if (!apiKey || !from) { res.statusCode = 503; res.end(JSON.stringify({ error: 'Email is not configured. Add RESEND_API_KEY and RESEND_FROM_EMAIL in Vercel.' })); return; }
  const remark = escapeHtml(bill.remark || '—');
  const date = escapeHtml(new Date(bill.createdAt || Date.now()).toLocaleString('en-IN'));
  const billId = escapeHtml(bill.id);
  const paidTo = escapeHtml(bill.upi || '7538090063@ptaxis');
  const amountText = amount.toFixed(2);
  const html = `<!doctype html><html><body style="margin:0;background:#f4f4f2;font-family:Arial,sans-serif;color:#171717">
  <div style="max-width:520px;margin:24px auto;background:#fff;padding:28px;border:1px solid #ddd">
    <div style="text-align:center"><div style="font-size:12px;letter-spacing:3px;color:#777">MIXOLOGY POS</div><h1 style="margin:8px 0 4px;font-size:25px">Payment Receipt</h1><div style="font-size:12px;color:#777">Payment acknowledgement</div></div>
    <div style="border-top:1px dashed #999;border-bottom:1px dashed #999;margin:22px 0;padding:14px 0">
      <p style="margin:7px 0"><b>Bill No.</b><span style="float:right">${billId}</span></p>
      <p style="margin:7px 0"><b>Date</b><span style="float:right">${date}</span></p>
      <p style="margin:7px 0"><b>Payment</b><span style="float:right">UPI</span></p>
      <p style="margin:7px 0"><b>Paid to</b><span style="float:right">${paidTo}</span></p>
      <p style="margin:7px 0"><b>Remark</b><span style="float:right">${remark}</span></p>
    </div>
    <div style="text-align:center;font-size:12px;color:#777">TOTAL PAID</div>
    <div style="text-align:center;font-size:32px;font-weight:800;margin:4px 0 20px">₹${amountText}</div>
    <div style="text-align:center;font-size:11px;color:#777">This is a payment acknowledgement generated by Mixology POS.</div>
  </div></body></html>`;
  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ from, to: [to], subject: `Mixology POS Receipt — ${billId}`, html, text: `Mixology POS\\nPayment Receipt\\nBill: ${billId}\\nAmount: ₹${amountText}\\nPayment: UPI\\nPaid to: ${paidTo}\\nRemark: ${remark}\\nDate: ${date}\\nStatus: PAID` }),
    });
    const result = await response.json().catch(() => ({}));
    if (response.status < 200 || response.status >= 300) { res.statusCode = 502; res.end(JSON.stringify({ error: result?.message || 'Email provider rejected the message.' })); return; }
    res.statusCode = 200; res.end(JSON.stringify({ sent: true, id: result?.id }));
  } catch { res.statusCode = 502; res.end(JSON.stringify({ error: 'Could not connect to the email provider.' })); }
}
